# 
resources:
  repositories: 
  - repository: Weight-tracker-terraform-pipeline
    type: github
    name: sincros121/Weight-tracker-terraform-pipeline
    endpoint: sincros121
    ref: main
    trigger:
      branches:
        include:
        - main
      paths:
        exclude:
          - azure-pipelines.yml
          - templates/*
          - templates


pool: 'self-hosted-stas'


stages:
- stage: Prepare_terraform
  displayName: Prepare terraform

  jobs:
    - job: Initialize_terraform
      displayName: Initialize terraform

      steps:
      - checkout: self
        displayName: Clone latest terraform repo

      - script: |
          terraform init
        displayName: Initialize terraform
        workingDirectory: root_module

    # - job: Workspaces
    #   displayName: Ensure workspaces exist
    #   dependsOn: Initialize_terraform

      # steps:
      - script: |
          terraform workspace new stage
        displayName: Ensure workspace stage exist
        workingDirectory: root_module

      - script: |
          terraform workspace new prod
        displayName: Ensure workspace prod exist
        workingDirectory: root_module



- stage: Stage_infrastructure
  displayName: Stage infrastructure deploy

  variables: 
  - group: vault secrets - stage

  jobs:
  - deployment: Deploy
    environment: stage
    strategy:
      runOnce:
        deploy:
          steps:            
          - task: DownloadSecureFile@1
            name: prod_tfvars
            displayName: 'Download prod tfvars file'
            inputs:
              secureFile: 'prod.tfvars'
            
          - script: |
              terraform workspace select $(Environment.Name)
            displayName: Select workspace
            workingDirectory: root_module
            

          - script: |
              terraform apply -var-file "$(prod_tfvars.secureFilePath)"
            displayName: Deploy infrastructure using .tfvars file
            workingDirectory: root_module
 


- stage: Prod_infrastructure
  displayName: Prod infrastructure deploy

  variables: 
  - group: vault secrets - prod

  jobs:
  - deployment: Deploy
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadSecureFile@1
            name: prod_tfvars
            displayName: 'Download prod tfvars file'
            inputs:
              secureFile: 'prod.tfvars'    
            
          - script: |
              terraform init
            displayName: Initialzie terraform
            workingDirectory: root_module

          - script: |
              terraform workspace select $(Environment.Name)
            displayName: Select workspace
            workingDirectory: root_module

          - script: |
              terraform apply -var-file "$(prod_tfvars.secureFilePath)"
            displayName: Deploy infrastructure using .tfvars file
            workingDirectory: root_module

